### ISSUE TITLE
Inconsistent status icons

### ISSUE THREAD

**Issue by jfabellera** [walterimaican/nightlight#1]
The light mode icon is a light switch while the dark mode icon is a moon. It would make more sense to have a light switch that is on for light mode and off for dark mode, or have a sun for light mode and a moon for dark mode.

**Comment by walterimaican** [comment]
Agreed, those icons are temporary to ensure that the program is properly toggling. Need to either get free-to-use icons or make them.

**Comment by walterimaican** [comment]
Custom icons have been created and added to this repo -> sun and moon for consistency. Closing issue.
