### ISSUE TITLE
NOT AN ISSUE WITH THE PROGRAM - What is the VS Code them in the screenshots in README.md?

### ISSUE THREAD

**Issue by mreed4** [walterimaican/nightlight#26]
What is the VS Code them in the screenshots in README.md? I like the color palette!

**Comment by walterimaican** [comment]
The theme is called Remedy! I tweaked one of the settings to be able to see some text more easily in the terminal: 

![image](https://user-images.githubusercontent.com/65641903/139596766-345ee2f0-42fa-4354-b767-dc9dac6c7dc7.png)

Here's a link to the official VS Code extension for the theme: https://marketplace.visualstudio.com/items?itemName=robertrossmann.remedy
